### ISSUE TITLE
Would it be possible to support both gadget and host USB modes?

### ISSUE THREAD

**Issue by lucaong** [nerves-project/nerves_system_rpi0#110]
Hello,
first of all thanks a lot for the awesome Nerves, I cannot be grateful enough to the maintainers!

I have one IoT application running on Nerves, and using the Rpi Zero W, that needs USB host capabilities. This project clearly documents how only USB gadget mode is supported, so I created my own custom version derived from it, in which I just change a few of the kernel configurations to enable host mode. My changes do little more than just reverting some of the configuration that was introduced by commits that force gadget mode.

I know that the docs suggest to use `nerves_system_rpi` instead, but `nerves_system_rpi0` already works well with the on-board WiFi module, that I make use of, so it was easier for me to customize it instead.

Now my boards seem to work well with both USB host and gadget mode, at least on my Mac. I was therefore curious if there is a specific reason to support only gadget mode. I assume it was a motivated decision, but I am curious about it.

The Rpi Zero W is one of the least expensive, smallest, Wifi-enabled boards out there, so it makes a lot of sense to use it also for USB host applications, and therefore I think it would be amazing to support both, OTG style, if that's a possibility.

Of course I can share my configuration, but again it's mostly looking as it was in this repo before disabling host mode. I also apologize in advance if I am missing something obvious, as I am not a huge expert on USB standards.

**Comment by ConnorRigby** [comment]
Could you share your custom system if it is open source? We've investigated this a lot and usually it gets shelved due to time required. I'd be interested to see the changes required and the compromises needed (if any)

**Comment by fhunleth** [comment]
This is part of the reason why we support people making custom systems. Everyone has different needs. The default systems reflect what we think we can support. Historically, we've had issues with USB reliability on the Raspberry Pis so I've been hesitant to add any more complexity. I think that I've fixed those and we haven't seen issues for the past couple months. Feel free to PR updates to support this. Just keep in mind that most people are using gadget mode and whatever the change is, it shouldn't require them to change their projects to support.

**Comment by lucaong** [comment]
thanks @fhunleth for the clarification. @ConnorRigby let me clean up the project-specific parts and publish my custom system open source. I did not experience any problem with it myself, and it does not seem to require any change for using gadget mode (e.g. IEx console over OTG port works out of the box). As it mirrors settings how they used to be in this repo though, and they were introduced for a reason as you explain, I would not be surprised to find that there are issues with it on other operative systems or configurations.

**Comment by lucaong** [comment]
as a final note, an alternative would be to add support for the Rpi Zero W on-board WiFi to `nerves_system_rpi`, which supports host mode (or is it already implemented and I just could't get it to work)
