### ISSUE TITLE
Switch USB Gadget Ethernet/Serial to Ethernet-only g_ether driver

### ISSUE THREAD

**Issue by fhunleth** [nerves-project/nerves_system_rpi0#133]
I've been running with `g_ether` for a week and it has been working solidly on Linux. Looking at the `g_ether` comments, I think that it exposes an RNDIS driver for Windows too. I'm so happy with how it runs, that I want to switch.

Here are the options:

1. Just switch and give up unauthenticated console access. Now that we can modify the erlinit.config via the `config.exs`, maybe it's not so bad to manually redirect to ttyAMA0 if low level debug is needed.
2. Finish off the USB gadget filesystem work

The main hurdles to be solved with the second option are to make USB come up with a good default out of the box, be easily configurable in a declarative way, and find time to review and update docs. One of the thoughts was to make the Nerves systems `runtime: true` and have them hold and apply the default. 

Given everything else going on, I'm leaning to giving up unauthenticated console access. That seems like a small price for making gadget USB usable for most Linux laptops again.

**Comment by mobileoverlord** [comment]
I think we should implement option 1 while we continue to hone in on option 2. The only time that I have ever used the serial console over the gadget interface has been to troubleshoot an application start failure. I choose the connection stability and support over having this feature.
