### ISSUE TITLE
nerves_system_rpi0 ~> 1.12.1 URL release not found 

### ISSUE THREAD

**Issue by FGMGIT** [nerves-project/nerves_system_rpi0#165]
### Environment

* Elixir 1.10.4 (compiled with Erlang/OTP 23)
* nerves_bootstrap| Environment Package List

  Pkg:         nerves_toolchain_ctng
  Vsn:         1.7.2
  
  Pkg:         nerves_toolchain_armv6_rpi_linux_gnueabi
  Vsn:         1.3.2
  
  Pkg:         nerves_system_br
  Vsn:         1.12.0

  Pkg:         nerves_system_rpi0
  Vsn:         1.12.1

Nerves environment
  MIX_TARGET:   rpi0
  MIX_ENV:      dev

### Current behavior

I was working in 1.12.1 nerves_system_rpi0 target and added some deps, elixircom and vintage_net_mobile and mix deps.get give me error, that firmware was built two days ago without problems

```
Resolving Nerves artifacts...
  Resolving nerves_system_rpi0
  => Trying https://github.com/nerves-project/nerves_system_rpi0/releases/download/v1.12.1/nerves_system_rpi0-portable-1.12.1-D1BD424.tar.gz
     Status 404 Not Found
  => Trying https://github.com/nerves-project/nerves_system_rpi0/releases/download/v1.12.1/nerves_system_rpi0-portable-1.12.1-D1BD42401726C92EB2328B96D03A0158644E17924FF3869E14661815E723D1D1.tar.gz
     Status 404 Not Found
  => no_result
```

The path to the release on GitHub point to:

`https://github.com/nerves-project/nerves_system_rpi0/releases/download/v1.12.1/nerves_system_rpi0-portable-1.12.1-0D8B7B0.tar.gz`

The tar filename is different

**Comment by fhunleth** [comment]
That means that something has changed in the `nerves_system_rpi0` source directory and we don't have a precompiled version of the system with those changes. If you want the changes, you'll have to build the system yourself. If you don't want them, then I'd `rm` `deps/nerves_system_rpi0` and run `mix deps.get` again to get it fresh.
