### ISSUE TITLE
Remove boot messages from HDMI output

### ISSUE THREAD

**Issue by fhunleth** [nerves-project/nerves_system_rpi0#28]
Since we're not using the HDMI output on the Raspberry Pi Zero, turn off the kernel messages that go there. This has an additional benefit of making the display look more professional for those putting displays on their Pi Zeros.

**Comment by mobileoverlord** [comment]
Fixed in master
https://github.com/nerves-project/nerves_system_rpi0/commit/1ab5ddc5aba6a3a03b30f9b0145e06e8540e27f5
