### ISSUE TITLE
Expose an RNDIS interface for Windows users

### ISSUE THREAD

**Issue by mdsebald** [nerves-project/nerves_system_rpi0#29]
Currently do not have an RNDIS Ethernet interface exported on the RPi Zero

**Comment by tmecklem** [comment]
Does Windows support a CDC Ethernet device? I know it didn't used to be the case, but I thought recent versions added support.

**Comment by fhunleth** [comment]
My understanding of the issue is that Windows doesn't come with a CDC Ethernet driver. I don't know if there's a free one that available. It seems that both the BBB and Raspbian have gone the route of exposing two Ethernet interfaces (one for RNDIS and one for ECM).

**Comment by tmecklem** [comment]
Related to https://github.com/nerves-project/nerves_system_rpi0/pull/27 if we can push that work forward.

**Comment by fhunleth** [comment]
Yeah, I'm pretty opposed to merging #27. I'll comment there.

**Comment by tmecklem** [comment]
#46 is related

**Comment by fhunleth** [comment]
Fixed in https://github.com/nerves-project/nerves_system_rpi0/releases/tag/v1.10.2.
