### ISSUE TITLE
Fresh nerves project does not compile

### ISSUE THREAD

**Issue by Visic** [nerves-project/nerves_system_rpi0#34]
Caveat:: I'm not sure if this is a problem with nerves_system_rpi0, or if it is with the version 0.12.0 of nerves_toolchain_armv6_rpi_linux_gnueabi.

Steps to reproduce:
mix nerves.new nerves_test
cd nerves_test
export MIX_TARGET=rpi0
mix deps.get
mix firmware

Failure:
==> nerves_test
Unchecked dependencies for environment dev:
* nerves_toolchain_armv6_rpi_linux_gnueabi (Hex package)
  could not find an app file at "_build/rpi0/dev/lib/nerves_toolchain_armv6_rpi_linux_gnueabi/ebin/nerves_toolchain_armv6_rpi_linux_gnueabi.app". This may happen if the dependency was not yet compiled, or you specified the wrong application name in your deps, or the dependency indeed has no app file (then you can pass app: false as option)
** (Mix) Can't continue due to errors on dependencies

Note:: if you target rpi instead (which uses 0.11.0 of the arm toolchain), "mix firmware" will work correctly.

**Comment by ConnorRigby** [comment]
Just confirmed. @mobileoverlord Did the new toolchain break?

**Comment by ConnorRigby** [comment]
interesting `https://github.com/nerves-project/nerves_system_rpi0/blob/master/mix.exs#L45` It says `app: false`

**Comment by ConnorRigby** [comment]
@Visic We reverted to a previous release, so if you remove your `mix.lock` file, you should be able to rebuild again :crossed_fingers:

**Comment by Visic** [comment]
@ConnorRigby Deleting the mix.lock files, doing "mix deps.get", and "mix firmware" does work correctly again.

Thank you for your help. 

I'm pretty new to nerves and elixir, but it would be interesting to learn what the problem is.

**Comment by ConnorRigby** [comment]
We actually don't know what the problem is yet. We kind of cheated because no one internally has much time to tackle the real issue at the moment. I'm going to reopen for now, since the _actual_ issue wasn't fixed.

**Comment by fhunleth** [comment]
@Visic Thank you so much for reporting this! Both Justin and I built projects with the new system before publishing it, but it is amazing how a fresh new project triggered this issue.

**Comment by fhunleth** [comment]
@mobileoverlord fixed the issue. I tested it on a clean project, so I think that we're good now!
