### ISSUE TITLE
RedBear IoT pHAT needs config.txt tweak for stable WiFi

### ISSUE THREAD

**Issue by tmecklem** [nerves-project/nerves_system_rpi0#5]
While troubleshooting a performance issue, @stwf discovered that adding init_uart_clock=48000000 modifies the SDIO clock for WiFi from 40 MHz to 20MHz, which increased reliability. This appeared to be the underlying cause for the performance issue. Reference: https://github.com/redbear/IoT_pHAT/tree/master/eeprom/experimental#version

We should add a note to the README for using the RedBear IoT pHAT and perhaps a comment to the config.txt file describing the change and why one might want to enable it.

**Comment by fhunleth** [comment]
Wow!

**Comment by fhunleth** [comment]
@tmecklem Did you want to add a short note to the README and call this one done? Or maybe we just close this now that the RPi Zero W is widely available?

**Comment by tmecklem** [comment]
I'd say we just close it. I have three and I never plan to use them now that the w is around.

**Comment by fhunleth** [comment]
Done.
