### ISSUE TITLE
Kernel Panic when Wifi network goes away, then comes back

### ISSUE THREAD

**Issue by stwf** [nerves-project/nerves_system_rpi0#70]
This is easily recreateable for me. I have a Nerves device running nicely on a wifi network. Take down the network and wait a minute, until you see the device react to the lack of network. Then Bring the network up again. Within a couple of minutes I see a kernel panic and the device is completely frozen.

<img width="842" alt="screen shot 2018-09-05 at 2 14 33 pm" src="https://user-images.githubusercontent.com/468262/45195522-ffcd9f80-b225-11e8-8de9-7ac088dc56c5.png">

**Comment by stwf** [comment]
The issue has been documented online in this post, and the fix proscribed there does fix this issue for me.
https://www.raspberrypi.org/forums/viewtopic.php?t=206083

So I made a PR that incorporates this. Not sure how you feel about including drivers downloaded from a website, but figured I'd post it. And it fixes this issue for me.

**Comment by fhunleth** [comment]
Any updates on this?

**Comment by stwf** [comment]
Yes, just confirmed updating to the latest nerves components fixes this!

**Comment by fhunleth** [comment]
Great! Thanks for following up.
