### ISSUE TITLE
Serial console broken since 1.5.1 on some host Linux installations 

### ISSUE THREAD

**Issue by ConnorRigby** [nerves-project/nerves_system_rpi0#79]
I just tried upgrading an application to 1.5.1 and i didn't get a console on usb0 on my host machine, and usb ethernet gadget didn't seem to work either.

**Comment by mobileoverlord** [comment]
I think I see what you are talking about. I get IEx on an ssh console, but not on the main usb console.

**Comment by ConnorRigby** [comment]
im also having some driver issues on linux: 
```
cdc_acm 1-1:1.2: failed to set dtr/rts
```

**Comment by ConnorRigby** [comment]
I was able to get an ip address and a solid serial connection, but after a firmware update, it was back to just eating my input and not doing anything. Also in `screen` it would just eat my `ctrl-a` input for some reason.

**Comment by ConnorRigby** [comment]
downgrading to 1.4.0 seems to give a reliable connection

**Comment by ConnorRigby** [comment]
I've been  investigating this a bit more today. It might be something specific to `screen`.
I tried using  `screen` on  a linux 4.9 and linux 4.14 (host) machine, and it worked properly. Both 4.19 and the latest 4.20 rc6 seem to have issues.

I tried a console via `dterm` on 4.19 and 4.20 and it worked. I'm going to close this issue as not really the fault of the rpi..

**Comment by ConnorRigby** [comment]
Re opening because it would seem that this is not fixed even on later Linux versions
https://github.com/nerves-project/nerves_network/issues/74#issuecomment-453027671
https://github.com/nerves-project/nerves_network/issues/74#issuecomment-453028542

**Comment by fhunleth** [comment]
This is fixed in #106. Thanks for this issue. It made me look in a direction that I wasn't investigating for the USB flakiness issue (#103). I really hope to get a proper release out soon.

**Comment by ConnorRigby** [comment]
Thanks for all the investigation @fhunleth !
